server:
    port: 8081
---
spring:
    config:
        activate:
            on-profile: "development"
server:
    port: 8080
---
spring:
    config:
        activate:
            on-profile: "test"
server:
    port: 8082
---
spring:
    config:
        activate:
            on-profile: "production"
server:
    port: 9000
